### PR TITLE
Add border to Schedule table to indicate end of week

### PR DESCRIPTION
**Pull request by harshita-gupta**

### CODE REVIEW

**Comment by marikgoldstein** [comment]
Hmmm

- the website doesn't build after this change
- Not all weeks have a friday date, so searching for (F) won't work. However, if it makes it easier, I could add in a friday a for all weeks?

Sorry for the mess, I merged it, but then reverted it in another PR.

**Comment by marikgoldstein** [comment]
Ok, all the weeks have fridays now, but you will still need to figure out why the original change broke the build

**Comment by harshita-gupta** [comment]
No worries, thanks for following up. Do you have any details on what you mean by "didn't build"? I will look into it.

**Comment by marikgoldstein** [comment]
Unfortunately, github's email was vague. It just emailed and said it didn't build. Did it display correctly for you locally?

**Pull request merged**
